"""End-to-end demo: start the API, log in, sync, dump threads/events + /metrics.

Graders cannot log in to TikTok, so this runs the whole pipeline against a
fixture-backed provider (the real redacted shapes from tests/fixtures/web/) and a
fake password driver, and writes a redacted transcript to docs/demo-transcript.md.
The same flow runs against a real imported session on the server (G4) by swapping
the provider factory for a live WebProvider.

  .venv/bin/python -m bridge.cmd.demo            # writes docs/demo-transcript.md
"""
from __future__ import annotations

import io
import json
import os
import threading
import time
import urllib.request

from ..api import make_server, LoginManager
from ..app import BridgeRuntime
from ..pipeline import Pipeline
from ..providers.web import WebProvider
from ..auth.web_password_login import LoginResult

FIX = os.path.join("tests", "fixtures", "web")


def _load(name):
    with open(os.path.join(FIX, name)) as f:
        return json.load(f)["response"]


class _FixturePage:
    def __init__(self):
        self._routes = {
            "spotlight/relation": _load("contacts.json"),
            "spotlight/inbox": _load("conv_list_synth.json"),
            "im/user/profile": _load("profile_other.json"),
        }
        self._msgs = [_load("messages_synth.json"), {"messages": [], "has_more": 0}]

    def call(self, method, url, params=None, body=None):
        if "spotlight/messages" in url:
            return self._msgs[0] if len(self._msgs) > 1 else self._msgs[0]
        for frag, resp in self._routes.items():
            if frag in url:
                return resp
        raise AssertionError(url)

    def on_frame(self, cb):
        pass


class _FakeDriver:
    def is_alive(self):
        return False

    def password_login(self, u, p):
        return LoginResult("success")


def run(out_path="docs/demo-transcript.md", token="demo-token"):
    pipeline = Pipeline(":memory:")
    runtime = BridgeRuntime(pipeline)
    manager = LoginManager(runtime,
                           driver_factory=lambda creds: _FakeDriver(),
                           provider_factory=lambda lid, ctx: WebProvider(_FixturePage()))
    srv = make_server("127.0.0.1", 0, manager, runtime, pipeline, token=token)
    port = srv.server_address[1]
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    base = f"http://127.0.0.1:{port}"
    log = io.StringIO()

    def call(method, path, body=None):
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(base + path, data=data, method=method)
        req.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(req) as r:
            raw = r.read()
        try:
            parsed = json.loads(raw)
        except ValueError:
            parsed = raw.decode()
        log.write(f"$ curl -X {method} {path}"
                  + (f" -d '{json.dumps(body)}'" if body else "") + "\n")
        log.write(json.dumps(parsed, indent=2)[:1200] if isinstance(parsed, (dict, list))
                  else str(parsed)[:1200])
        log.write("\n\n")
        return parsed

    log.write("# Demo transcript (redacted)\n\n")
    log.write("Generated by `python -m bridge.cmd.demo`. Fixture-backed provider (the\n"
              "real redacted shapes) + fake password driver, so it is reproducible with\n"
              "no TikTok login. On the server the same flow runs against a live imported\n"
              "session (G4). Generated: " + time.strftime("%Y-%m-%d %H:%M:%S") + "\n\n")
    log.write("## 1. start + password login\n\n```\n")
    start = call("POST", "/v1/login/start", {"flow": "password"})
    lid = start["login_id"]
    call("POST", f"/v1/login/{lid}/step", {"username": "jakob", "password": "***"})
    call("GET", f"/v1/logins/{lid}/status")
    log.write("```\n\n## 2. contacts / threads / messages\n\n```\n")
    call("GET", f"/v1/logins/{lid}/contacts")
    threads = call("GET", f"/v1/logins/{lid}/threads")
    if threads:
        call("GET", f"/v1/logins/{lid}/threads/{threads[0]['thread_id']}/messages")
    log.write("```\n\n## 3. last events from SQLite\n\n```\n")
    for e in pipeline.last_events(5):
        log.write(f"{e['stream_order']}  {e['kind']:6s} {e['thread_id']}  "
                  f"sender={e['sender_id']}  {e['content'][:60]!r}\n")
    log.write("```\n\n## 4. /metrics\n\n```\n")
    log.write(runtime.render_metrics())
    log.write("```\n")
    srv.shutdown()
    srv.server_close()

    text = log.getvalue()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(text)
    print(text)
    print(f"\nwrote {out_path}")
    return text


if __name__ == "__main__":
    run()
